### ISSUE TITLE
Define associations for Donations, Beneficiary

### ISSUE THREAD

**Issue by Rukorio-Vanessa** [Rukorio-Vanessa/tuinue-wasichana#46]
The following associations should be defined for these models:

1. Beneficiary
- [x] belongs_to :charity, class_name: 'User'
- [x] belongs_to :donor, class_name: 'User'
- [x] has_many :inventories, through: :charity

2. Donation

- [x]  belongs_to :donor, class_name: 'User'
- [x] belongs_to :charity, class_name: 'User'

**Comment by Bernardkoech** [comment]
defined all associations for Donations and beneficiaries
